title: Your awesome title
author: GitHub User
email: miniruby14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Civil Engineer, Facility Management & Data Scientist

# social links
twitter_username: Ruby Quan
github_username:  miniruby14

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
